name: text_to_image
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.2


  get_it: ^7.2.0
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: 3.2.3
  shimmer: ^2.0.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10

  get: ^4.6.5
  http: ^0.13.5
  lottie: ^2.1.0
  keyboard_dismisser: ^3.0.0
  share_plus: ^6.3.0
  dio: ^4.0.6
  permission_handler: ^10.2.0
  image_downloader: ^0.31.0
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^13.0.0
  intl: ^0.17.0
  timeline_tile: ^2.0.0
  rive: ^0.9.1
  flutter_svg: ^1.1.6
  flutter_neumorphic: ^3.2.0
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  image_picker: ^0.8.6
  adaptive_dialog: ^1.8.2
  url_launcher: ^6.1.8
  in_app_review: ^2.0.6
  shared_preferences: ^2.0.17
  flutter_zoom_drawer: ^3.0.3
  intl_phone_number_input: ^0.7.2
  glassmorphism: ^3.0.0
  path_provider: ^2.0.12
  google_mobile_ads: ^2.3.0
  flutter_stripe: ^8.0.0+1
  flutter_dotenv: ^5.0.2
  rflutter_alert: ^2.0.4
  google_sign_in: ^6.0.2
  rounded_loading_button: ^2.1.0
  font_awesome_flutter: ^10.4.0
  flutter_facebook_auth: ^5.0.8
  flutter_login_facebook: ^1.7.0
  flutter_pdfview: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/pdfs/
  fonts:
    - family: poppins-bold
      fonts:
        - asset: assets/fonts/poppins-bold.ttf

    - family: poppins-semi-bold
      fonts:
        - asset: assets/fonts/poppins-semibold.ttf

    - family: inter-regular
      fonts:
        - asset: assets/fonts/inter-regular.ttf

    - family: inter-semibold
      fonts:
        - asset: assets/fonts/inter-semibold.ttf

    - family: urbanist-bold
      fonts:
        - asset: assets/fonts/urbanist-bold.ttf

    - family: urbanist-medium
      fonts:
        - asset: assets/fonts/urbanist-medium.ttf


